################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[en.params]
home = "Home"
# copyright
copyright = "Copyright &copy; 2025 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)"



################################### Arabic language #####################################
[languages.ar]
languageName = "العربية"
languageCode = "ar"
contentDir = "content/ar"
weight = 2
languageDirection = "rtl"

[languages.ar.params]
home = "الرئيسية"

# copyright
copyright = "© جميع الحقوق محفوظة لمدرسة ابن كثير الإسلامية 2025 | سياسة الخصوصية | عناوين الاتصال"

