################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[en.params]
home = "Home"
# copyright
copyright = " &copy; 2025 Ibun Kathir School All Rights Reserved | Designed by [gamuun dhijitaal](https://gamuun.com/)"



################################### Arabic language #####################################
[languages.ar]
languageName = "العربية"
languageCode = "ar"
contentDir = "content/ar"
weight = 2
languageDirection = "rtl"

[languages.ar.params]
home = "الرئيسية"
# copyright
copyright = " &copy; جميع الحقوق محفوظة لمدرسة ابن كثير الإسلامية 2025"

